export default {
    AUTH: "AUTH",
    AUTH_WITHOUT_REGISTRATION: "AUTH_WITHOUT_REGISTRATION",
    LOGOUT: "LOGOUT",
    RATE: "RATE",
    REMOVE_TOKEN: "SYSTEM_REMOVE_TOKEN",
    ADD_TOKEN: "SYSTEM_ADD_TOKEN",
}
