export default {
    ADD_SERVICE: "ADD_SERVICE",
    DELETE_SERVICE: "DELETE_SERVICE",
    CHANGE_CURRENT_MILEAGE: "CHANGE_CURRENT_MILEAGE",
    ADD_TYPE: "MILEAGE_ADD_TYPE",
    DELETE_TYPE: "MILEAGE_DELETE_TYPE",
}
