export default {
    ADD_TRANSPORT: "ADD_TRANSPORT",
    DELETE_TRANSPORT: "DELETE_TRANSPORT",
    CHANGE_CURRENT_TRANSPORT: "CHANGE_CURRENT_TRANSPORT",
    EDIT_TRANSPORT: "EDIT_TRANSPORT",
    CHANGE_MILEAGE: "CHANGE_MILEAGE"
}
