name: Build and deploy

on:
  release:
    branches: [ master ]
    paths-ignore: '.github/**'
    types: [ published ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - uses: actions/checkout@master
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.MOTO_HELP_FIREBASE_TOKEN }}
