name: Build and deploy

on:
  push:
    branches: [ master ]
    paths-ignore: '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Prepare SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: moto.help
      - name: Install
        run: |
          npm i --no-cache
     # - name: Lint
     #   run: npm run lint
      - name: Build
        run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        env:
          HOST: "moto.help"
          USERNAME: "root"
          KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          source: "./public/*"
          target: "/var/develop/moto-help-api/project/public"
          strip_components: 1


